//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineStudio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AVRISP_MKII")]
        public string CurrentProgrammer {
            get {
                return ((string)(this["CurrentProgrammer"]));
            }
            set {
                this["CurrentProgrammer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Stk500")]
        public string AVRISP_MKII {
            get {
                return ((string)(this["AVRISP_MKII"]));
            }
            set {
                this["AVRISP_MKII"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Raptor")]
        public string CurrentDevice {
            get {
                return ((string)(this["CurrentDevice"]));
            }
            set {
                this["CurrentDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AVRISP_MKII")]
        public string Programmers {
            get {
                return ((string)(this["Programmers"]));
            }
            set {
                this["Programmers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RAPTOR,MINIDAL,MS6,SQSPEEDO_V2,SQSPEEDO_V1,LEACH,PHAROS_TX,PHAROS_RX,ULOGGER,XPOR" +
            "TLAN,RTTEMP,")]
        public string Devices {
            get {
                return ((string)(this["Devices"]));
            }
            set {
                this["Devices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Verify {
            get {
                return ((bool)(this["Verify"]));
            }
            set {
                this["Verify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Raptor,ATMega128.hex,RAPTOR_EEP2.hex,RAPTORV5_3P.hex,D0AF,CF,ATMEGA128")]
        public string RAPTOR {
            get {
                return ((string)(this["RAPTOR"]));
            }
            set {
                this["RAPTOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MinDal,MINIDAL16_V1_5_BOOT.hex,MiniDal16_EEP.hex,,D22D,CF,ATMEGA16")]
        public string MINIDAL {
            get {
                return ((string)(this["MINIDAL"]));
            }
            set {
                this["MINIDAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MS6,BootLoad.hex,,RTMTEMP_V1_7D.hex,D02D,CF,ATMEGA128")]
        public string MS6 {
            get {
                return ((string)(this["MS6"]));
            }
            set {
                this["MS6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQSpeedo,ATMega128.hex,SqSpeedo EEPROM.hex,TACHOVMU_V1_4F.hex,D0AF,CF,ATMEGA128")]
        public string SQSPEEDO_V2 {
            get {
                return ((string)(this["SQSPEEDO_V2"]));
            }
            set {
                this["SQSPEEDO_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQSpeedo,ATMega128.hex,SqSpeedo EEPROM.hex,TACHOVMU_V1_2V.hex,D02D,CF,ATMEGA128")]
        public string SQSPEEDO_V1 {
            get {
                return ((string)(this["SQSPEEDO_V1"]));
            }
            set {
                this["SQSPEEDO_V1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Leach,ATMega128.hex,,LEACHPRG3_6O.hex,D02F,CF,ATMEGA128")]
        public string LEACH {
            get {
                return ((string)(this["LEACH"]));
            }
            set {
                this["LEACH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pharos\\\\TX,proj.hex,,,D02D,CF,ATMEGA8")]
        public string PHAROS_TX {
            get {
                return ((string)(this["PHAROS_TX"]));
            }
            set {
                this["PHAROS_TX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pharos\\\\RX,PROJ_RRQ3.hex,gjs_eeprom.hex,,D12D,CF,ATMEGA8")]
        public string PHAROS_RX {
            get {
                return ((string)(this["PHAROS_RX"]));
            }
            set {
                this["PHAROS_RX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uLoggerUSB,,,ULOGGERUSB.hex,D0AF,CF,ATMEGA32")]
        public string ULOGGER {
            get {
                return ((string)(this["ULOGGER"]));
            }
            set {
                this["ULOGGER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XPortLAN,,,XPortCom.hex,D0AD,CF,ATMEGA128")]
        public string XPORTLAN {
            get {
                return ((string)(this["XPORTLAN"]));
            }
            set {
                this["XPORTLAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RT Temp,BootLoad.hex,,RTMTemp_V1_5E,D02D.hex,CF,ATMEGA64")]
        public string RTTEMP {
            get {
                return ((string)(this["RTTEMP"]));
            }
            set {
                this["RTTEMP"] = value;
            }
        }

        #region VMU_CFG
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string downloadFolder
        {
            get
            {
                return ((string)(this["downloadFolder"]));
            }
            set
            {
                this["downloadFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<NONE>")]
        public string profilePath
        {
            get
            {
                return ((string)(this["profilePath"]));
            }
            set
            {
                this["profilePath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eepromFilePath
        {
            get
            {
                return ((string)(this["eepromFilePath"]));
            }
            set
            {
                this["eepromFilePath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D0AF")]
        public string fuseBits
        {
            get
            {
                return ((string)(this["fuseBits"]));
            }
            set
            {
                this["fuseBits"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CF")]
        public string lockBits
        {
            get
            {
                return ((string)(this["lockBits"]));
            }
            set
            {
                this["lockBits"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string flashFilePath
        {
            get
            {
                return ((string)(this["flashFilePath"]));
            }
            set
            {
                this["flashFilePath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bootFilePath
        {
            get
            {
                return ((string)(this["bootFilePath"]));
            }
            set
            {
                this["bootFilePath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string avrDeviceIndex
        {
            get
            {
                return ((string)(this["avrDeviceIndex"]));
            }
            set
            {
                this["avrDeviceIndex"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string programmerIndex
        {
            get
            {
                return ((string)(this["programmerIndex"]));
            }
            set
            {
                this["programmerIndex"] = value;
            }
        }
        #endregion

        #region vPoll
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DATA")]
        public string dataPath
        {
            get
            {
                return ((string)(this["dataPath"]));
            }
            set
            {
                this["dataPath"] = value;
            }
        }

        /*[global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Leach,0,0,0,epNumber,0,115200,10.0.0.7,1,1171,Data")]
        public string leach
        {
            get
            {
                return ((string)(this["leach"]));
            }
            set
            {
                this["leach"] = value;
            }
        }*/

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string selectedIndex
        {
            get
            {
                return ((string)(this["selectedIndex"]));
            }
            set
            {
                this["selectedIndex"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string cardReaderPort
        {
            get
            {
                return ((string)(this["cardReaderPort"]));
            }
            set
            {
                this["cardReaderPort"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string cardReaderBaud
        {
            get
            {
                return ((string)(this["cardReaderBaud"]));
            }
            set
            {
                this["cardReaderBaud"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string cardFileNo
        {
            get
            {
                return ((string)(this["cardFileNo"]));
            }
            set
            {
                this["cardFileNo"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string uid
        {
            get
            {
                return ((string)(this["uid"]));
            }
            set
            {
                this["uid"] = value;
            }
        }
        #endregion
    }
}
